import { readFileSync, existsSync, readdirSync } from 'fs'
import { join, basename } from 'path'
import bundledRegistry from '@/lib/agents.json'
import type { Agent } from '@/lib/types'

/** Raw agent data from JSON (everything except runtime-loaded soul and crons) */
export type AgentEntry = Omit<Agent, 'soul' | 'crons'>

/** Color palette assigned to auto-discovered agents */
const DISCOVER_COLORS = [
  '#f5c518', '#a855f7', '#3b82f6', '#22c55e', '#f97316',
  '#eab308', '#14b8a6', '#60a5fa', '#f59e0b', '#94a3b8',
  '#06b6d4', '#ec4899', '#84cc16', '#8b5cf6', '#ef4444',
]

// ---------------------------------------------------------------------------
// Heading / identity extraction helpers (exported for testing)
// ---------------------------------------------------------------------------

/**
 * Parse a SOUL.md heading into a clean agent name and optional title.
 *
 * Handles all observed heading formats:
 *   "# SOUL.md — VERA"                 → name "VERA"
 *   "# SOUL.md — KAZE, Flight Research Agent" → name "KAZE", title "Flight Research Agent"
 *   "# ECHO — Community Voice Monitor" → name "ECHO", title "Community Voice Monitor"
 *   "# SOUL.md - Who You Are"          → name null (not a useful agent name)
 *   "# QUILL — Herald's Content Writer" → name "QUILL", title "Herald's Content Writer"
 */
export function parseSoulHeading(content: string): { name: string | null; title: string | null } {
  const match = content.match(/^#\s+(.+)/m)
  if (!match) return { name: null, title: null }

  let heading = match[1].trim()

  // Strip "SOUL.md — ", "SOUL.md - ", "SOUL.md:" prefixes
  heading = heading.replace(/^SOUL\.md\s*[—–\-:]\s*/i, '')

  // If the heading is generic (e.g. "Who You Are"), it's not a useful agent name
  if (/^who\s+you\s+are/i.test(heading)) return { name: null, title: null }

  // Split on em-dash / en-dash to separate name from description
  const dashParts = heading.split(/\s*[—–]\s*/)
  const nameAndMaybeTitle = dashParts[0].trim()
  const descAfterDash = dashParts.length > 1 ? dashParts.slice(1).join(' — ').trim() : null

  // The name might contain a comma: "LUMEN, SEO Team Director"
  const commaParts = nameAndMaybeTitle.split(/,\s*/)
  const name = commaParts[0].trim() || null
  const titleFromComma = commaParts.length > 1 ? commaParts.slice(1).join(', ').trim() : null

  const title = titleFromComma || descAfterDash || null
  return { name, title }
}

/**
 * Parse an IDENTITY.md file for agent name and emoji.
 *
 * Expected format (generated by OpenClaw bootstrap):
 *   - **Name:** Jarvis
 *   - **Emoji:** 🤖
 */
export function parseIdentity(content: string): { name: string | null; emoji: string | null } {
  const nameMatch = content.match(/\*\*Name:\*\*\s*(.+)/i)
  const emojiMatch = content.match(/\*\*Emoji:\*\*\s*(\S+)/i)
  return {
    name: nameMatch ? nameMatch[1].trim() : null,
    emoji: emojiMatch ? emojiMatch[1].trim() : null,
  }
}

/**
 * Convert a directory slug to a display name: "my-agent" -> "My Agent"
 */
function slugToName(slug: string): string {
  return slug
    .split(/[-_]/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

/**
 * Read a file and return its content, or null on any error.
 */
function safeRead(filePath: string): string | null {
  try {
    if (!existsSync(filePath)) return null
    return readFileSync(filePath, 'utf-8')
  } catch {
    return null
  }
}

/**
 * Scan a directory for sub-agent .md files (e.g. sub-agents/QUILL.md, members/WRITER.md).
 * Returns an array of { fileName, content } for each .md file found.
 */
function scanSubAgentDir(dirPath: string): { fileName: string; content: string }[] {
  if (!existsSync(dirPath)) return []
  try {
    return readdirSync(dirPath)
      .filter(f => f.endsWith('.md'))
      .map(f => {
        const content = safeRead(join(dirPath, f))
        return content ? { fileName: f, content } : null
      })
      .filter((x): x is { fileName: string; content: string } => x !== null)
  } catch {
    return []
  }
}

// ---------------------------------------------------------------------------
// Auto-discovery
// ---------------------------------------------------------------------------

/**
 * Auto-discover agents from $WORKSPACE_PATH.
 *
 * Scans the workspace for:
 *   - IDENTITY.md at root (for root agent name/emoji)
 *   - SOUL.md at root (root orchestrator)
 *   - agents/<dir>/SOUL.md (top-level agents)
 *   - agents/<dir>/sub-agents/*.md (nested sub-agents)
 *   - agents/<dir>/members/*.md (team member agents)
 *
 * Returns null if nothing can be discovered.
 */
function discoverAgents(workspacePath: string): AgentEntry[] | null {
  const agentsDir = join(workspacePath, 'agents')
  const rootSoulPath = join(workspacePath, 'SOUL.md')
  const identityPath = join(workspacePath, 'IDENTITY.md')
  const hasRoot = existsSync(rootSoulPath)

  // Scan agents/ directory for all subdirectories (even without SOUL.md, may have sub-agents)
  let allAgentDirs: string[] = []
  if (existsSync(agentsDir)) {
    try {
      const entries = readdirSync(agentsDir, { withFileTypes: true })
      allAgentDirs = entries.filter(e => e.isDirectory()).map(e => e.name)
    } catch {}
  }

  // Need at least a root or agent directories to discover
  if (!hasRoot && allAgentDirs.length === 0) return null

  const discovered: AgentEntry[] = []
  let colorIndex = 0

  // --- Root agent ---
  let rootId = 'main'
  let rootName = 'Main'
  let rootEmoji = '\u{1F916}'

  if (hasRoot) {
    // Try IDENTITY.md first (most reliable source for name/emoji)
    const identityContent = safeRead(identityPath)
    if (identityContent) {
      const identity = parseIdentity(identityContent)
      if (identity.name) {
        rootName = identity.name
        rootId = identity.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'main'
      }
      if (identity.emoji) rootEmoji = identity.emoji
    }

    // Fall back to SOUL.md heading if IDENTITY.md didn't provide a name
    if (rootName === 'Main') {
      const soulContent = safeRead(rootSoulPath)
      if (soulContent) {
        const parsed = parseSoulHeading(soulContent)
        if (parsed.name) {
          rootName = parsed.name
          rootId = parsed.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'main'
        }
      }
    }

    // Collect all agent IDs that report to root (including those without SOUL.md but with sub-agents)
    const directReportIds: string[] = []

    discovered.push({
      id: rootId,
      name: rootName,
      title: 'Orchestrator',
      reportsTo: null,
      directReports: directReportIds, // populated below
      soulPath: 'SOUL.md',
      voiceId: null,
      color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
      emoji: rootEmoji,
      tools: ['read', 'write', 'exec', 'message'],
      memoryPath: null,
      description: 'Top-level orchestrator.',
    })

    // We'll fill directReportIds as we discover agents below
    for (const dirName of allAgentDirs) {
      const hasSoul = existsSync(join(agentsDir, dirName, 'SOUL.md'))
      const hasSubAgents = existsSync(join(agentsDir, dirName, 'sub-agents'))
      const hasMembers = existsSync(join(agentsDir, dirName, 'members'))
      if (hasSoul || hasSubAgents || hasMembers) {
        directReportIds.push(dirName)
      }
    }
  }

  // --- Top-level agents ---
  for (const dirName of allAgentDirs) {
    // Skip if directory name matches the root agent ID (already added above)
    if (hasRoot && dirName === rootId) continue

    const soulFile = join(agentsDir, dirName, 'SOUL.md')
    const hasSoul = existsSync(soulFile)
    const subAgentsDir = join(agentsDir, dirName, 'sub-agents')
    const membersDir = join(agentsDir, dirName, 'members')
    const hasSubAgents = existsSync(subAgentsDir)
    const hasMembers = existsSync(membersDir)

    // Skip directories with nothing useful
    if (!hasSoul && !hasSubAgents && !hasMembers) continue

    let name = slugToName(dirName)
    let title = 'Agent'
    const subAgentIds: string[] = []

    // Parse SOUL.md for name and title
    if (hasSoul) {
      const content = safeRead(soulFile)
      if (content) {
        const parsed = parseSoulHeading(content)
        if (parsed.name) name = parsed.name
        if (parsed.title) title = parsed.title

        // Also check for Role: or Title: lines as fallback
        if (title === 'Agent') {
          const roleMatch = content.match(/^##\s*Role\b/mi)
          if (roleMatch) {
            // Try to get first line after ## Role
            const afterRole = content.slice(roleMatch.index! + roleMatch[0].length)
            const firstLine = afterRole.match(/\n\s*\n(.+)/)?.[1]?.trim()
            // Don't use long role descriptions as titles
            if (firstLine && firstLine.length < 80) title = firstLine
          }
        }
      }
    }

    // Discover sub-agents (sub-agents/ and members/ directories)
    const subAgentFiles = [
      ...scanSubAgentDir(subAgentsDir),
      ...scanSubAgentDir(membersDir),
    ]

    for (const sub of subAgentFiles) {
      const subId = `${dirName}-${basename(sub.fileName, '.md').toLowerCase()}`
      subAgentIds.push(subId)

      const subParsed = parseSoulHeading(sub.content)
      const subName = subParsed.name || slugToName(basename(sub.fileName, '.md'))
      const subTitle = subParsed.title || 'Agent'

      discovered.push({
        id: subId,
        name: subName,
        title: subTitle,
        reportsTo: dirName,
        directReports: [],
        soulPath: null, // sub-agents use non-standard paths, soul loaded differently
        voiceId: null,
        color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
        emoji: subName.charAt(0).toUpperCase(),
        tools: ['read', 'write'],
        memoryPath: null,
        description: `${subName} agent.`,
      })
    }

    discovered.push({
      id: dirName,
      name,
      title,
      reportsTo: hasRoot ? rootId : null,
      directReports: subAgentIds,
      soulPath: hasSoul ? `agents/${dirName}/SOUL.md` : null,
      voiceId: null,
      color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
      emoji: name.charAt(0).toUpperCase(),
      tools: ['read', 'write'],
      memoryPath: null,
      description: `${name} agent.`,
    })
  }

  return discovered.length > 0 ? discovered : null
}

/**
 * Load the agent registry.
 *
 * Resolution order:
 *   1. $WORKSPACE_PATH/clawport/agents.json  (user's own config)
 *   2. Auto-discovered from $WORKSPACE_PATH   (agents/ directory scan)
 *   3. Bundled lib/agents.json               (default example registry)
 */
export function loadRegistry(): AgentEntry[] {
  const workspacePath = process.env.WORKSPACE_PATH

  if (workspacePath) {
    // 1. User-provided override
    const userRegistryPath = join(workspacePath, 'clawport', 'agents.json')
    if (existsSync(userRegistryPath)) {
      try {
        const raw = readFileSync(userRegistryPath, 'utf-8')
        return JSON.parse(raw) as AgentEntry[]
      } catch {
        // Malformed user JSON -- fall through
      }
    }

    // 2. Auto-discover from workspace
    const discovered = discoverAgents(workspacePath)
    if (discovered) return discovered
  }

  // 3. Bundled fallback
  return bundledRegistry as AgentEntry[]
}
